# Generated by Django 4.0.1 on 2022-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
